#! /bin/bash


#
# Usage: ./convert=accounting-file.sh <input file> 
#   - input_file: outout file generated by ./get-s3-accounting.sh
#


cat $1 | jq '[ .[][] | {MessageFormatVersion: .MessageFormatVersion, Date: .date, FE: .FE, ChargeGroup: .charge_group, ChargeRole: .charge_role, WallClockHours: 0, CPUHours: 0, DiskQuota: .quota_raw, DiskUsage: .usage_raw, Prenormalised: false, Dedicated: false}]  '  | jq  'group_by(.ChargeGroup) | map({MessageFormatVersion: .[0].MessageFormatVersion, Date: .[0].Date, FE: .[0].FE, ChargeGroup: .[0].ChargeGroup, ChargeRole: "default", WallClockHours: 0, CPUHours: 0, DiskUsage: map(.DiskUsage) | add, DiskQuota: map(.DiskQuota) | add, Prenormalised: false, Dedicated: false})' 
