#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status.
set -e

# Exit if inactive
HOSTNAME=$(hostname -s)
ceph daemon mds.${HOSTNAME} status 2>/dev/null | jq -e '.state == "up:active"' &> /dev/null


# Get current mds_max_caps_per_client (or 20000 if not defined)
# TODO this is not working on mimic because the option is not available
#MAX_CAPS=$(ceph daemon mds.${HOSTNAME} config show | jq -r '[.mds_max_caps_per_client + 0, 20000]|max')
MAX_CAPS=20000
ceph daemon mds.${HOSTNAME} session ls | jq ".[]|select(.num_caps>$((10*MAX_CAPS)))"
